---

- name  : Create consul group
  group :
    name : "{{ consul_group }}"

- name : Create consul user
  user :
    name : "{{ consul_user }}"

- name                   : Download consul binary
  ansible.builtin.get_url :
    url  : https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest : /tmp/consul{{ consul_version }}.zip

- name      : Expand consul binary
  unarchive :
    src        : /tmp/consul{{ consul_version }}.zip
    dest       : /usr/local/bin
    remote_src : true
  notify    : Restart consul service

- name      : Create directories for consul
  file      :
    path  : "{{item}}"
    state : directory
    owner : consul
    group : consul
    mode  : "0750"
  with_items :
    - "{{ consul_config_dir }}"
    - /opt/consul
    - /opt/consul/data
    - "{{ consul_tls_dir }}"

- name     : Check for encryption key
  stat     :
    path : "{{ encryption_key_file }}"
  register : key_file_present 
  when     : ("consul_servers" in group_names)

- name    : Generate encryption key
  shell   : consul keygen
  register : consul_encryption_key
  when     : not key_file_present.stat.exists and ("consul_servers" in group_names)
  run_once : true

- name     : Store in local file
  copy     :
    content : consul_encryprion_key.stdout
    dest    : "{{ encryption_key_file }}"
    mode    : 0600
  when     : not key_file_present.stat.exists and ("consul_servers" in group_names)
  run_once : true

- name     : Cat encryption key
  shell    : cat {{ encryption_key_file }}
  register : consul_encryption_key
  when     : ("consul_servers" in group_names)
  run_once : true

- name     : Create common consul config file
  template :
    src  : common-config.hcl.j2
    dest : "{{ consul_config_dir }}common-config.hcl"
  notify   : Restart consul service

- name     : Create consul service file
  template :
    src  : consul.service.j2
    dest : /etc/systemd/system/consul.service
  notify   : Restart consul service

- name            : Enable consul service
  systemd_service :
    state : started
    name  : consul.service
